services:
    # Builder
    kryptopus_candlestick_storage_elasticsearch_builder:
        class: "domain/StorageBuilder"
        tags:
            - { name: kryptopus.candlestick_storage_builder, builder_id: elasticsearch }

    # Command to test elasticsearch connection
    kryptopus_command_test_storage_elasticsearch_connection:
        class: "application/command/TestConnectionCommand"
        arguments:
            - "@kryptopus_candlestick_storage_elasticsearch_builder"
        tags:
            - { name: "solfege.console.command" }


    # Command to save a candle
    kryptopus_command_save_candle_on_elasticsearch:
        class: "application/command/SaveCandleCommand"
        arguments:
            - "@kryptopus_candlestick_storage_elasticsearch_builder"
        tags:
            - { name: "solfege.console.command" }

    # Command to get candles in period
    kryptopus_command_get_candles_in_period_on_elasticsearch:
        class: "application/command/GetInPeriodCommand"
        arguments:
            - "@kryptopus_candlestick_storage_elasticsearch_builder"
        tags:
            - { name: "solfege.console.command" }


